### ISSUE TITLE
type error in HHE report data entry

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1024]
When editing data in an existing chemical record entry in the modal pop up, data was edited, and on pressing 'save' on the modal pop up, the following error was seen:

TypeError at /datadocument/1367252/
__str__ returned non-string (type NoneType)

Data document page can now not be accessed at all: http://factotum.epa.gov/datadocument/1367252/

Data group type is HH

Definition of Done:
data document page (http://factotum.epa.gov/datadocument/1367252/) can be viewed, and chemical record can be edited without error.

**Comment by debboutr** [comment]
this is happening from the `__str__` method that we have currently defined on the `ExtractedHHRec` model, it is currently:

```
# dashboard/models/extracted_hhrec.py
...
    def __str__(self):
        return self.raw_chem_name
...

```
Because we have the arguments on `raw_chem_name` setup w/ `null=True, blank=True`, the null value will be `None` in python or `NULL` in the DB. This is problematic for the `__str__` method that we use above.  Here is an example of the difference w/ using `null=True` vs. `null=False`
```
In [1]: from dashboard.models import *                                                                                    

In [2]: et = ExtractedText.objects.filter(data_document__data_group__group_type__code='HH').first()                       

In [3]: ExtractedHHRec.objects.create(extracted_text=et)                                                                  
Out[3]: ---------------------------------------------------------------------------
TypeError: __str__ returned non-string (type NoneType)
```
**!!! this will save this as a record, but will have NULL for it's raw_chem_name value,
 which will throw this error any time you try to look up this instance in python !!!**

**ExtractedHabitsAndPractices has a similar`__str__` method**
```
    def __str__(self):
        return self.product_surveyed
```
**BUT, when saved w/o a product_surveyed value it evals to ''**

```
In [4]: et = ExtractedText.objects.filter(data_document__data_group__group_type__code='HP').first()                       

In [5]: hnp = ExtractedHabitsAndPractices.objects.create(extracted_text=et)                                               

In [6]: str(hnp)                                                                                                          
Out[6]: ''

In [7]: hnp.product_surveyed                                                                                              
Out[7]: ''
``` 
We have been getting around this in other model `__str__` methods like so:
```
    def __str__(self):
        return str(self.raw_chem_name) if self.raw_chem_name else ""
```
but, if we refer to the django docs, we probably should never be using `null=True` on any of our CharField or TextField definitions.

[https://docs.djangoproject.com/en/2.2/ref/models/fields/#null](https://docs.djangoproject.com/en/2.2/ref/models/fields/#null)
> Avoid using null on string-based fields such as CharField and TextField. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL. One exception is when a CharField has both unique=True and blank=True set. In this situation, null=True is required to avoid unique constraint violations when saving multiple objects with blank values.

**Comment by kdionisio** [comment]
should be resolved in Rhinoceros Beetle sprint
