### ISSUE TITLE
faceted search for product and data document (20 points)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#104]
Implement faceted search within application. Desire ability to search on Products by title, with the following two facets

1. Data documents, by type of data document (e.g. no data document, MSDS, SDS, ingredient list, etc.)
2. Product category, by general category (e.g., no product category, list of ~12 general categories)

Search bar appears on far right side of the navigation bar, on every page of the application. User enters a product title in the search bar. User is then taken to a landing page with search results on product title, with the two facets visible on the left side of the page.

**Comment by mwfrost** [comment]
django-haystack looks promising:

http://django-haystack.readthedocs.io/en/master/tutorial.html

**Comment by mwfrost** [comment]
Current prototype uses elasticsearch for its back end. 
Version 2.4 of elasticsearch is the most recent version supported by haystack

**Comment by kdionisio** [comment]
Discussed via phone with @mwfrost to clarify - for now implement as:

1. search on product title, facet by product category
2. search on data document, facet by data document type (but this can only be done once #125 is complete, since the data document type does not yet exist); for now can implement a search on data document title but with no facets
