### ISSUE TITLE
modifications to extraction_script model (5 points)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#108]
As Damien the data collector
I want to store multiple types of scripts
So that I can track which scripts were used for different functions, and on different data sets.

The current extraction_script model needs to be generalized, and will store *all* scripts associated with the data.

Script being stored will remain a GitHub link. A new field needs to be added to the model for 'script_type.' The type of script needs to be modifiable from the admin interface.

Types of scripts we currently have:
- download
- extraction
- product categorization

**Comment by debboutr** [comment]
our ExtractionScript model currently has fields for `title` **and** `url`, might it make sense to combine these into one field based off of `url`?
```
>>> url = 'https://github.com/HumanExposure/factotum/blob/master/dashboard/migrations/0001_initial.py'
>>> title = url.split('/')[-1]
>>> title
'0001_initial.py'
```
this way, we don't need to store both in the table

**Comment by kdionisio** [comment]
@debboutr We currently do not have a product categorization script!! As of now it doesn't exist in Factotum at all (not anywhere in the data models, and not anywhere in the application). I included it as an example of the 3 different types of scripts that we know will be stored in the new 'script data model' moving forward.

For some background, the product categorization scripts will come in when we start applying some scripts to large batches of data documents to do semi-automated product categorization (rather than categorizing products one-by-one, manuallly, which is currently what the application allows for).
