### ISSUE TITLE
file type error in uploading extracted text

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1104]
After the push of Uncas Skipper sprint, Factotum users are having trouble uploading extracted text files. Users are seeing an 'unknown file type' Value Error.

Note that users have attempted to upload 16 different extracted text .csv files, in 3 different data groups. Of the 16, 6 have uploaded successfully, 10 have given unknown file type errors. In attempting to determine the difference between files which uploaded successfully and those which did not, the only difference appears to be the number of records in the file. In the successful uploads, number of records in each file was always below 18,000. In the unsuccessful uploads, number of records in each file was always above 18,000.

Definition of Done:
Upload of extracted text file does not give error.

Example of file that was not successful in the upload is attached below, which is an upload for this data group on prod http://factotum.epa.gov/datagroup/506/
[https://app.zenhub.com/files/99837877/b7f6bfd4-507b-456c-ba67-4afc9973b1c1/download](https://app.zenhub.com/files/99837877/b7f6bfd4-507b-456c-ba67-4afc9973b1c1/download)

**Comment by fang-yan-csra** [comment]
Increase the upload file max memory to 5MB in settings.py allows the attached sample file to be processed without the "unknown file type" error. 

#FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880

However, testing the attached file locally with production db from 9/30 takes a long time. The performance deteriorates as record size in the uploaded extracted text CSV file goes up.
Some stop watch profiling collection:
1000 records
clean took 0.591876745223999
is_valid took 32.62245583534241
save - update document took 0.04183197021484375
save - create parent took 19.024303913116455
save - create child took 19.18921971321106
save took 38.26292085647583

2000 records
clean took 2.490515947341919
is_valid took 67.27067589759827
save - update document took 0.0840599536895752
save - create parent took 38.162819147109985
save - create child took 38.64444303512573
save took 76.89956903457642

5000 records
clean took 19.87935519218445
is_valid took 181.14215087890625
save - update document took 0.1416921615600586
save - create parent took 96.83223080635071
save - create child took 96.57304406166077
save took 193.55066204071045

The is_valid() and save() call time seems linear to the record size. Because of the parent/child relation nature of Extracted Text, we cannot use bulk insert on this model. Which means we really don't have much space to improve the performance. Schedule a backend job to process the file seems an alternate option instead of process it synchronously.

**Comment by dmlyons2** [comment]
Dave will look at adjusting the above settings on `production` and discuss a ticket rewrite to fix this if needed.

**Comment by kdionisio** [comment]
note - for now keep file upload sizes at ~ <18,000 records for successful uploads
