### ISSUE TITLE
functional use model diagram

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1340]
Specify new data model for functional use relationships

Definition of Done:
Data diagram of proposed new data model structure

**Comment by mwfrost** [comment]
This diagram shows the status quo inheritance relationship between ExtractedFunctionalUse and RawChem, which will be replaced in ticket 1322 with a one-to-many relationship.

![erd_before.png](https://images.zenhubusercontent.com/5be34a63f724c70c7221c972/96932d45-3c3e-4d3d-8d01-1dde6b2c96e9)

**Comment by mwfrost** [comment]
![erd_before](https://user-images.githubusercontent.com/201835/72534557-e0884e80-382b-11ea-94f4-6457126b6e86.png)

The same image, but with an annotation asking about Composition data. 

We talked on the call about how every ExtractedChemical record can only have one `reported_funcuse` value, since the functional use is specific to the composition in which the chemical appears. But if we are extending the ExtractedFunctionalUse model in #1323 and #1326 with additional fields and curation metadata, it would make sense to enhance the functional use field for ExtractedChemicals in the same way.

**Comment by debboutr** [comment]
@mwfrost here's what I was thinking for the new table created...
```
# this new setup will leave RawChem as the model that name/cas will be loaded into and
# then this table will have many funcuses that can be associated with the same chemical, one
# if the difficulties will be how to register. One way might be to have all the funcuses
# splittable in the CSV column by a given char, i.e. "," or ";" and the bulk_upload would create
# one record for each. This table name could stay ExtractedFunctionalUse I just changed it
# to show that it is a wholly new table.
class ReportFuncuse(CommonInfo): 
    
    chem = models.ForeignKey(
        "RawChem",
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    
    report_funcuse = models.CharField(
        "Reported functional use", max_length=255, null=True, blank=True
    )
```

**Comment by debboutr** [comment]
the child model for the group type will change
```

**Comment by mwfrost** [comment]
Right, the child model for a Functional Use data document would become RawChem because there's no corresponding model for a *chemical* that has been extracted for functional use analysis. Our current data model uses `ExtractedFunctionalUse` at this level in the data hierarchy, but that no longer makes sense. All the other models that inherit from `RawChem` do so because they add type-specific attributes to a chemical record. This series of tickets is all about relating multiple functional use objects to a single chemical record.

**Comment by mwfrost** [comment]
It might be safer for us to keep a model in that place, inheriting from `RawChem`, just in case there turn out to be other attributes that only apply to chemicals from FU documents. The `report_funcuse` field would be replaced by a set of related functional use records

**Comment by debboutr** [comment]
I like it, I also forgot that CommonInfo isn't in the RawChem model, but in each of it's inherited models.
```
class ExtractedFunctionalUse (CommonInfo, RawChem):
    pass

class ReportFuncuse(CommonInfo): 
    
    chem = models.ForeignKey(
        "ExtractedFunctionalUse ",
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    
    report_funcuse = models.CharField(
        "Reported functional use", max_length=255, null=True, blank=True
    )
```

**Comment by mwfrost** [comment]
Good stuff, this is why I wanted this to have its own ticket.

How about this version of your suggestion, where I've added the fields from ticket #1323 ?
```
class ExtractedFunctionalUseChem (CommonInfo, RawChem):
    pass

class FunctionalUse(CommonInfo): 
    
    chem = models.ForeignKey(
        "ExtractedFunctionalUseChem ",
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    
    report_funcuse = models.CharField(
        "Reported functional use", max_length=255, null=True, blank=True
    )
    clean_funcuse = models.CharField(
        "Cleaned functional use", max_length=255, null=True, blank=True
    )
```
Ticket 1323 has us adding the `clean_funcuse` field to both `ExtractedChemical` and `ExtractedListPresence`. If instead we used a foreign key to link those models to the `FunctionalUse` model, we would only have to add the cleaned field(s) in one place. It creates the need for a data migration, though.

**Comment by debboutr** [comment]
this looks good, and with the tables named this way we can create them, then populate with what exists, and then blow away the old `ExtractedFunctionalUse` table.

APROVED

**Comment by debboutr** [comment]
this looks good, and with the tables named this way we can create them, then populate with what exists, and then blow away the old `ExtractedFunctionalUse` table.

APPROVED

**Comment by debboutr** [comment]
this last post from @mwfrost shows the relationship of the `FunctionalUse` table linking to `RawChem` and then any chemical table w/ `report_funcuse` will use this table to hold the value.
