### ISSUE TITLE
resolve PUC assignment conflicts

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1358]
As a Factotum data curator
I want the ability to resolve PUC assignment conflicts
So that I can ensure I have the highest quality data

Currently, the dashboard_producttopuc model allows for a user to assign a PUC to a product using multiple different methods (e.g. manual assignment of PUC, batch assignment of PUC, batch assignment through raw category, or scripted assignment of PUC)

Definition of Done:
- Link from data curation menu in nav bar to page for 'Resolve PUC conflicts'
- Link would bring user to a page with a table listing all products which have multiple PUCs assigned, where the PUC assignments are not consistent (e.g. a product assigned to 'shampoo' PUC via manual but assigned to 'air freshener' PUC via scripted assignment)
  -Table should include columns for:
      - Product name (hyperlink to /product/ page)
      - one of the assigned PUCs (hyperlink to /PUC/ page)
      - Method of assignment for above PUC (i.e. classification method)
      - conflicting assigned PUC (hyperlink to /PUC/ page)
      - Method of assignment for above PUC

**Comment by mwfrost** [comment]
After looking at this with production data, it's apparent that the database includes a lot of duplicate Product records. The table includes the Product ID in order to distinguish between cases where one product is assigned to multiple PUCs an cases where it's just two Product records with identical Title attributes.
