### ISSUE TITLE
upload product images

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1376]
As a data curator
I need to upload images associated with products
So that I can display the image on the /product/ page

Often, when a curator is batch uploading product data via a .csv upload on the /datagroup/ page, the curator also has the associated image files with the image of the product. There is currently not a way to upload these product images.

Definition of Done:
Ability for curator to batch upload images associated with products

*One idea for a workflow
- Curator batch uploads product data via .csv (this functionality already exists). In the batch product upload file, user indicates, for each product, the filename for the product image; filename for product image is stored
- For data groups with existing products, functionality exists on /datagroup/ page to batch upload image files (similar to how documents are uploaded). If user uploads image files, application will look for filenames which match the product image filenames previously stored

**Comment by michael-barbour** [comment]
![image](https://user-images.githubusercontent.com/22226925/76125301-8190bb80-5fca-11ea-8883-0c89a6c8054a.png)


In order to get this to work with a CSV upload, I'm going to model the workflow after the Data Document workflow.  The steps to upload a Product image are:
- Upload a csv file with and additional header image_name
- Upload a directory/folder of images
- Submit both at the same time

The program will then match newly created products with images based on the file name.  If you upload a csv with `my_image.png` it will search the directory/folder for `my_image.png` and upload them as a pair.

In order to make sure this is set up correctly I want you to sign off on some assumptions I need to make about what counts as incorrect data.

Case 1: No image directory or folder is attached
Response: Process as normal

Case 2: A csv row has no image.
Response: Create the Product as normal

Case 3: A csv row has an image listed and a match is found
Response: Create the Product and attach that image.

Case 4: An image is uploaded with no match.
Response: Ignore the Image and process the file as normal

**Case 5:** A csv row has an image listed and no match is found
Response: Return an error telling the user that row has an issue with the image_name.  **Do not create the product**.  Process other rows as normal

As of right now those are all the possible cases I can imagine causing problems.

**Comment by kdionisio** [comment]
In general I am good with this workflow. A couple of thoughts however to see if you want to refine. I am wondering if flexibility for the user is greater if they can 'register' the image filenames with the batch product upload file, but then upload the actual files as a separate step (this would mimic the workflow for 'registering' a data document as step 1, and then selecting the folder where data document files live for the files themselves to be uploaded as step 2). If this is more work then I would say stick with your proposed workflow.

Additional notes. Case 2, 3, 4 are good. 

Case 1 concerns me - what if the user just accidentally does not attach an image directory? I think there is actually Case 1a - if no image directory or folder is attached AND there are no image filenames listed in the entire csv upload, then process as normal. Case 1b - if no image directory or folder is attached BUT there is at least 1 image filename included in the csv, then user must confirm 'are you sure you want to upload batch product data without the image files?'

For Case 5, this would be fine, if the user clearly saw an error message after upload that said something like 'rows 1,2,3 were not processed because no matching image files were found. Please re-upload data for rows 1,2,3, either correcting the image filename or removing the image filename from the csv' (something like that)

**Comment by michael-barbour** [comment]
I considered your suggested workflow, but by removing the connection of doing the connection in a single upload, then I'll have to consider image name uniqueness.

Say data curator 1 is working on data group 1 and uploads a product with the file name `image_1.jpg`.  DC1 then uploads the image named `image_1.jpg` and the connection is made.

Data curator 2 also working on data group 1 makes a new product with the image named `image_1.jpg`.  When data curator 2 uploads his set of images to that data group, not only will his image upload to the newly created product, but it will also replace the product image that data curator 1 uploaded.

Even data curator 1's upload is question.  If for instance he had connected one of the data documents with an existing product and that product's image had been called `image_1.jpg` his upload would have replaced the previous image.

Without enforcing some constraint (ie file names must contain the UPC then a "-" or that bulk image uploads are not allowed to override existing images) it's hard for a data curator to know that their images are being attached appropriately.

**As for case 1b**, I was planning on case 5 still returning a warning if case 1b occurred.  If you were to upload a .csv file with an image_name but no image directory at all:
- All files without image_names would be created 
- Files with image_names would return a warning (because there is no matching image)

If you want me to check through all of the rows and give the user an **error message** then abort the process, that should be relatively easy.  If you want me to give the user a **confirmation alert**, that would harder as it would require me to rewrite CSV processing in JavaScript and add front end validation.

**Comment by kdionisio** [comment]
Got it - understood on the image name uniqueness and possible issues there. Go ahead with doing the upload as a single step.

Regarding case 1b - my only concern here is mistakes. e.g. if a file contains 100 image names, but user selects a folder that contains only 1 image file. Then all products are created but user sees a message that '99 products were created but did not have matching images'. User then has no way of loading in those matching images that they mistakenly didn't include to correct their mistake. 

Might be better to check all rows for image names and matching image files at initiation of upload. If there are image names present that do not have a matching image, entire upload is aborted and user sees an error message (ideally listing which records had an image file name but no matching image file). Then it is up to user to correct their mistake before they proceed.

**Comment by michael-barbour** [comment]
> Regarding case 1b - my only concern here is mistakes. e.g. if a file contains 100 image names, but user selects a folder that contains only 1 image file. Then all products are created but user sees a message that '99 products were created but did not have matching images'. User then has no way of loading in those matching images that they mistakenly didn't include to correct their mistake.

The curator would be able to reupload the rows.  The error message currently reads `The following record images could not be matched and were not added:` followed with a list of 99 data_document_ids** corresponding to the rows that had an issue.  These rows will **not** be created.  The next upload should contain the 99 image files as well as the csv containing the 99 rejected rows

The user could then place those rows in a new CSV and reupload them with the correct image directory and/or image_name.

> Might be better to check all rows for image names and matching image files at initiation of upload. If there are image names present that do not have a matching image, entire upload is aborted and user sees an error message (ideally listing which records had an image file name but no matching image file). Then it is up to user to correct their mistake before they proceed.

This is where I don't know enough on how curators use this system to make a call.  

If curators want to reupload the same CSV file with minor changes, then we shouldn't process any products to prevent duplicates.  Case 5 should then be
`Response: Return an error telling the curator that row has an issue with the image_name.`**`Do not process the CSV`**

If curators want to successfully create as many products as possible, then narrow down their CSV by removing created products from it, then case 5 is valid. The issue here is that if they accidentally refresh or close the warning, they will lose the record of which products were rejected.

Currently when we find a row that is an issue, specifically with the UPC, the other rows are processed and the problem row is returned in a warning without being processed.  That is the strategy I've been following.  If you would prefer the entire .csv to be rejected based on 1 problem row, that would be easy to implement and might be easier for curators.

**I'm concerned that I'm returning data document ids to identify rows with errors. I decided to use the IDs based on what the UPC check returns.  If data document ids are not unique, it might be worth changing this to be a unique key or combination.  Perhaps `product name` or `product name - data document id`?

**Comment by kdionisio** [comment]
I talked to the curators - I think the best option is to check for errors (i.e. missing files for image filenames) in the *whole* document, and if there are errors, reject the entire file. Curators agree with your worry - what if they lose the error message and don't know which rows were processed and which were not? Also it isn't super easy to merge a long list of IDs of files which were not processed that is presented in an error message in with their file. So, let's go all or nothing - either the whole file is processed, or the whole file is not processed.

For error message, please return the data document ID where the error occurred (OK if the data document ID is associated with multiple rows in the batch product .csv upload file.
