### ISSUE TITLE
time out on data upload

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1386]
Upon attempting to upload extracted text data via csv file into Factotum, user receives time out error because csv file is too large.

Error: "OperationalError: 2006,MySQL server has gone away"

csv user is attempting to upload is 30,690 rows, 4,440 KB

Definition of Done:
Ability to upload large files (as described above) via csv into the product/extracted text model

**Comment by mcovalt** [comment]
This is most likely due to a too large query being sent to MySQL in the [`inheritance_bulk_create`](https://github.com/HumanExposure/factotum/blob/e4ee8b81225c575246174601a981c49a3377a657/dashboard/utils.py#L393-L448) method. Possible solutions are:

- Increase `max_allowed_packet` on the MySQL server. This is the fastest solution with the highest probability for success, but I do not know what the negatives may be.
- Modify [`inheritance_bulk_create`](https://github.com/HumanExposure/factotum/blob/e4ee8b81225c575246174601a981c49a3377a657/dashboard/utils.py#L393-L448) (and calls to `bulk_create` and `bulk_update`) to send rows in batches. This should be straightforward, but will still need to be inside a transaction. Therefore, the issue may stand after this is implemented.
- Drop [`inheritance_bulk_create`](https://github.com/HumanExposure/factotum/blob/e4ee8b81225c575246174601a981c49a3377a657/dashboard/utils.py#L393-L448) and insert the rows one-by-one. This will result in a _significant_ increase in processing time, but this may be ameliorated with Celery. It would also simplify the codebase. The aforementioned concern regarding holding the transaction scope alive affects this as well.

**Comment by dmlyons2** [comment]
@mcovalt - it was set to 5M, I have upp'd it to 50M

**Comment by dmlyons2** [comment]
It was the mysql setting and is now working.
