### ISSUE TITLE
Selective Removal of Audit Log Triggers

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1395]
Each time the factotum database is migrated, the AuditLog class drops all the triggers in the schema and rebuilds all the audit log triggers on each model. This process would delete any unrelated triggers that had been added for other reasons, and would not rebuild them since they don't have corresponding audit log instructions in the models.

Requirement: the AuditLog class deletes only the triggers that were created for the Audit Log.

**Comment by zachmunzenrider** [comment]
I did some research into adding an `@auditable` decorator or custom attributes on model fields, as Fang suggested, but it doesn't look like Django supports either of those options.

I think the next best option is to keep the current optional `auditlog_fields()` method in our model classes, but rather than just skip models that don't have `auditlog_fields()`, we always generate matching `DROP TRIGGER IF EXISTS` statements in the SQL script. The overhead is negligible, but it will catch the edge cases Rick identified where a trigger could be orphaned if we were to remove `auditlog_fields()` from a particular model, without deleting potential future triggers that are unrelated to auditing.

This approach still wouldn't catch the case if we were to rename an entire model that has auditable fields, but if we're renaming models like that at this point, dropping the orphan triggers manually will be a very small part of that effort.
