### ISSUE TITLE
Assign PUC Problem

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#155]
When on the Product Curation Page, I click Assign Puc. I decide that I can not find a PUC and press cancel and get this error:

```DoesNotExist at /category_assignment/1
DataSource matching query does not exist.
data/code/factotum/dashboard/views/product_curation.py in category_assignment
        ds = DataSource.objects.get(pk=pk)
pk | '1'
request | <WSGIRequest: GET '/category_assignment/1'>
template_name | 'product_curation/category_assignment.html'

```

**Comment by mwfrost** [comment]
The URL destination for the link in the "Cancel" button was being built incorrectly. Instead of using the primary key of the Product's parent DataSource, it used the Product's PK. 

The URL has been corrected, and a new test has been added. The corrected branch is `dev_155`.

`python manage.py test dashboard.tests.functional_tests.TestPUCAssignment.test_cancelled_puc_assignment`
