### ISSUE TITLE
Audit Log Bug

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1677]
There appears to be a bug with the audit log on the QA summary page for composition documents.

Ex. https://factotum.epa.gov/qa/compextractionscript/343/summary
An error shows up when you click on the audit log entry for some documents.
There is a "DataTables Warning" popup, and the audit log never loads. 
It seems to show up when there is a deleted chemical record in the document. Maybe in these cases, when the chemical record is removed, the table becomes empty and there are no records associated with the document. 

![Audit log deleted record.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/defb053f-9aa3-4c60-b41c-3aba45eccb8e)

Definition of Done:
	• Audit log loads correctly for documents with no records
	• Track the deleted document record within the audit log, including all the applicable fields (updated at, updated by, etc)

**Comment by mwfrost** [comment]
We investigated this during the pointing meeting. We suspect that the queryset of the modal audit log list is prefetching `RawChem` records that no longer exist. When the model table displays the audit log records, the 

See `dashboard/views/qa.py SummaryTable.get_initial_queryset`, around line 260:
```
qs = (
            self.get_extractedtext_queryset()
            .annotate(
                has_qanotes=Exists(qa_subquery), has_updated_rc=Exists(rc_subquery)
            )
            .filter(Q(has_qanotes=True) | Q(has_updated_rc=True))
            .prefetch_related("rawchem")
            .select_related("qanotes", "data_document")
            .annotate(last_updated_rc=Max("rawchem__updated_at"))
            .annotate(
                last_updated=Case(
                    When(
                        data_document__updated_at__lte=F("last_updated_rc"),
                        updated_at__lte=F("last_updated_rc"),
                        then="last_updated_rc",
                    ),
                    When(
                        updated_at__lte=F("data_document__updated_at"),
                        last_updated_rc__lte=F("data_document__updated_at"),
                        then="data_document__updated_at",
                    ),
                    default=F("updated_at"),
                )
            )
            .annotate(rawchem_count=Count("rawchem"))
            .all()
        )
```
The "Updated At" dates shown in the modal table are not attributes of the `AuditLog` model. That model only contains references to the object that changed and a `date_created` record for itself. The "Updated At" values are derived by traversing over to the related record and performing the conditional logic shown above. We need to modify that code so that it doesn't try to look up deleted records.

**Comment by mwfrost** [comment]
http://127.0.0.1:8000/qa/compextractionscript/343/summary
