### ISSUE TITLE
Bulk Product Removal Pt. 1

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1802]
Part 1 is for creating the new page and table. 

As a data curator
I would like to display and search all products within a PUC
So that I can find products within a PUC that are miscategorized

After implementing the 'automatic' (AU) PUC classification method, many products were placed in incorrect PUCs. I would like to be able to search for products within a PUC, and quickly remove products that don’t belong in that PUC. 
I would like this to be similar to the Attribute assignment tool, where curators search by PUC. https://factotum.epa.gov/bulk_product_tag/ 
Then have the ability to select multiple products to remove them. 

Comments:
Once you remove the product-to-PUC relationship, can you reassign using that same method?
Would like the table to only display products in this PUC table when they are UberPUC assignments. 
Would this remove all PUC assignments, or just the 'top layer' or UberPUC assignment?

Definition of Done:
	• New page for bulk removal of product-to-PUC assignments
	• Ability to search by PUC name 
	• Ability to search by product name within table
	• Table displays columns for: 
		○ Product name
		○ Classification method

**Comment by michael-barbour** [comment]
> Once you remove the product-to-PUC relationship, can you reassign using that same method?

This ticket doesn't deal with the actual delete functionality as that is coming on part 2.

**For automatic processes: probably not.**
The best example of this would be if we were to design a process where products automatically get assigned to a PUC only when they are first saved.  Re-doing that process automatically after a change would probably be a mistake because it will simply put the data in the same state as before you deleted the connection.

If you want prevent this from happening perhaps preventing any automatic classification methods from showing up on this table would work.  They are deliberately low confidence for that reason.  Otherwise building in a place to "relaunch" those automatic assignments may be a better solution.  This would prevent the previously mentioned reassigning of data.

**For manual processes/tools: yes.**
If instead you're worried about breaking your ability to manually assign PUCs (such as via the product page or a tool like https://factotum.epa.gov/bulk_product_puc/), the functionality should not be effected.  The data will

> Would like the table to only display products in this PUC table when they are UberPUC assignments.

:+1:

> Would this remove all PUC assignments, or just the 'top layer' or UberPUC assignment?

That is up to you.  My expectation is that if this page shows only UberPUC assignments then only the UberPUC should be removed.

Removing all connections would be trivial but would possibly make something like re-running automatic processes a problem.
