### ISSUE TITLE
Delete Cleaned Composition Data

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2053]
As a product owner
I would like to delete cleaned composition records associated with a cleaning script
So that I can easily remove all cleaned weight fractions from documents within a data group. 

We currently have a tool in factotum that removes all 'extracted text' related to an extraction script from data documents. https://factotum.epa.gov/extractionscripts/delete/ 
I would like to develop a similar tool to remove all 'cleaned composition' data from documents, based on the associated cleaning script. 

Currently, there is no way to remove cleaned composition data from data documents. 
After we complete QA on the composition cleaning scripts, we might notice that there a systemic errors in the script, and we want to clear out all cleaned data associated with that script. So we need a tool to delete all cleaned data in data documents associated with a particular script. 
Then we can upload a new script and csv file with the corrected data using the upload tools on the /datagroup/ page. 

Definition of Done:
· Create a new page for Delete Cleaned Composition Data, similar to /extractionscripts/delete/
· List all Cleaning Scripts and include ability to delete all associated cleaned composition records.
· Ability to search table, paginate results.

**Comment by mwfrost** [comment]
@Sakshi-Handa ,
Because of how we store extracted composition data, this page will not actually delete any records. The raw and cleaned composition values are stored together in the `ExtractedComposition` model. Instead, this script will reset to null the values in `central_wf_analysis`, 'lower_wf_analysis`, and `upper_wf_analysis`, and will delete the script's QA group if one was created. 

The `raw_min_comp`, `raw_max_comp`, `raw_central_comp`, `weight_fraction_type`, `unit_type`, and `ingredient_rank` fields will remain as-is.

Does this match your understanding?

**Comment by Sakshi-Handa** [comment]
Yes, that works. As long as we can remove the cleaned weight fraction fields and associated cleaning script, so that we can upload a new script and populate new values in the wf_analysis fields
