### ISSUE TITLE
Upload extracted text (8 points)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#32]
Dependent on completion of #25 

As a data curator,
I want to upload the text extracted (outside of the system) from pdf documents,
So that I can track, manage, and summarize this text data within the application.

On the '[Data Group Show](https://balsamiq.cloud/sadlf/psb72/r465A)' page, the 'Upload Extracted Text' button will allow the user to upload a .csv file which contains the text extracted from a sub-set of documents. 

On the Data Group Show page, the link to .csv template under the 'Upload Extracted Text' button should be a template listing the below columns.

The .csv template/file uploaded must contain the following columns, in the following order (not required unless indicated):
- filename (required) 
- record_type (text, max 50 characters)
- prod_name (text, max 500 characters)
- cas (text, max 50 characters)
- chem_name (text, max 500 characters) 
- raw_min_comp (text, max 100 characters)
- raw_max_comp (text, max 100 characters)
- units (text, max 100 characters)
- report_funcuse (text, max 100 characters)
- doc_date (date, YYYY-MM-DD format)  
- rev_num (text, max 50 characters)

Data included in the uploaded .csv file will be inserted into data models as follows:
Note that the filename field in the uploaded .csv is what tells you which data document the extracted data corresponds to. Data in the uploaded .csv will be pushed into two different data models, extracted_text and extracted_chemical.

Fields from uploaded .csv file which will be entered into extracted_text data model are:
- record_type
- prod_name
- doc_date
- rev_num

Fields from uploaded .csv file which will be entered into extracted_chemical data model are:
- cas
- chem_name
- raw_min_comp
- raw_max_comp
- units
- report_funcuse

The user needs the option to select, from a drop down menu of all registered scripts in the scripts model, the single script which applies to the full file to be uploaded. This can happen immediately prior to file upload, or immediately after file upload, whichever works best.

Upon upload of the above .csv file of extracted text, for every record included in the uploaded .csv file of extracted text, the indicator in the 'extracted' column for each data record listed in the table at the bottom of the 'Data Group Show' page will be updated. In addition, text above the table will be updated.

**Comment by kdionisio** [comment]
@debboutr  Note the following changes above to the original ticket, re. the pt_comp field, and the changes regarding the 'script' identified with the file.
-

**Comment by debboutr** [comment]
does it make sense to load the CSV template w/ the Documents that have been matched but not extracted already?

i.e. we can add the filename, record_type, prod_name into the table before the download and even keep the pk of each DataDocument, because the way it is now assumes that the filename is unique and we don't have any checks or uniqueness on that field currently.

Also, there are a lot more fields than what I see in any of the branches made for this issue's **ExtractedText** model which leads me to believe I might be missing something, @zachmunzenrider  or @dmlyons2  please comment

**Comment by debboutr** [comment]
does it make sense to load the CSV template w/ the DataDocuments that have been matched but not extracted already?

i.e. we can add the filename, record_type, prod_name into the table before the download and even keep the pk of each DataDocument, because the way it is now assumes that the filename is unique and we don't have any checks or uniqueness on that field currently.

If we are linking this model to DataDocument, why are we storing record_type and prod_name in another table, doesn't seem too DRY, but I don't see it the way you do. I'm guessing you have tables all ready that have this data in them? In which case, we are going to match DataDocument to Extraction script through filename?

Actually, doesn't it also make sense to just add these new fields to the DataDocument itself? or could we have the same extracted text going to 2 different DataDocuments. I'm not sure that I see why it need it's own model, it is the data associated with the document.

**Comment by debboutr** [comment]
@kdionisio  @dmlyons2  what order of magnitude do you think we'll be having for DataGroups? I'm thinking of keeping a csv template for each Datagroup in static to serve. Also, will we want to retain the completed template on the file system when it's extracted?

**Comment by kdionisio** [comment]
I would guess number of data groups would be <1,000. And most likely, it
would be around 200-300 max for the forseeable future (with the exception
of what @dmlyons2 might be doing for Walmart - but I don't thhink Walmart
products are going to have data groups).

**Comment by debboutr** [comment]
How do we feel the file structure should look for the CSV's that have been uploaded w/ the extracted text?
I was thinking the `DataGroup` name, like so:

`'./static/csv/{data_group.title}/{filename}'`

I could also apply this to the `register_records.csv` to be stored in the same `{data_group.title}` folder for organization.

**Comment by debboutr** [comment]
there is currently no field in our models:
- prod_name (text) From product through data document

would this be the `title` from the associated `Product` or `DataDocument`??

_we are associating `ExtractedText` to the `DataDocument`, so on a `__str__` return of the `ExtractedText` model, I'm thinking we should get the `DataDocument.title`?_

`prod_name` will be acessible thru the `DataDocument`

Also, will the

- doc_date (date)

be in the uploaded CSV? or should it just be the time at which the `ExtractedText` model is instantiated?

if it comes from the CSV, what would be the format?
