### ISSUE TITLE
Data Docs - media/datasource problems (8 pts)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#363]
Users are starting to name data groups like MSDS, SDS, etc. There have also been instances where data groups have been renamed. This orphans data in the media directory.

The desired outcome is that a user can call a datagroup anything they want and have that abstracted from the media directory naming.

Def of Done:
- all new datagroups have an opaque name in the media directory such as datagroup id (PK) or a uuid 
- keep in mind that a datagroup type could change, say from unidentified to composition

Test: can rename a data group and calls to that data group still work after name has been changed

**Comment by mwfrost** [comment]
We completed this task using the approach mentioned in the original ticket: each data group's files go into a folder named for the DataGroup objects `id` attribute. Running unit tests with unpredictable primary key incrementing, however, showed that it won't work. We cannot name the upload folder as the data group is being created because there is no reliable way to know the PK of an object that has not yet been saved.
