### ISSUE TITLE
limit attributes available for each PUC (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#410]
As Kathie the Product Owner
I want the ability to assign 'available' PUC attributes to each PUC
so that I can limit the attributes a curator is allowed to assign to a product belonging to a certain PUC.

In #123, a model was created to store PUC attributes, and the ability to add PUC attributes in the admin interface was implemented.

We currently have the ability to add attributes to the attributes model. Please add the ability to, from the admin interface, associate attributes with PUCs, so that when a user is assigning attributes to a product, they are limited to only assigning attributes to the product which are associated with the PUC to which the product belongs.

e.g., for the PUC 'air freshener', I want to associate the attributes of spray, gel, and liquid to the PUC. When a user is editing the product 'Glade Lavender Scent Spray air freshener', and they assign the product to the air freshener category, the ONLY attributes they would have the option of assigning to the product would be spray, gel, or liquid. They could NOT assign the attribute 'solid' to the Glade product, since 'solid' is not an allowed attribute for the air freshener PUC.

Definition of Done: Ability to, in admin interface, associate attributes with specific PUCs
Test:

**Comment by mwfrost** [comment]
This is a revision of #123 , which added a ProductAttribute that's not dependent on the PUC. This new PUC-dependent PUCAttribute object model replaces the old ProductAttribute model. Each PUCAttribute has a parent PUC. Once a PUC is assigned to a Product, the Product can then be associated with zero to all of the PUCAttributes whose parents are the Product's UberPUC.

**Comment by zachmunzenrider** [comment]
As we just discussed in standup:

Back in June, Dave L created a PUCAttribute model and migration. This doesn’t appear to be used for anything.

I opted in my ticket to build off of the ProductAttribute model, adding a PUC foreign key. I considered renaming this model PUCAttribute, as Matt had suggested in his comment on this ticket, but decided to keep it as is. In part that’s because of the existing PUCAttribute model that Dave L created, but it also seems reasonable that the data represented by this model are still Product attributes, even though they are now constrained by PUC.

After discussion in standup, we agreed to delete the PUCAttribute model
