### ISSUE TITLE
QA - Edit/Approve extracted text (8 Points)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#46]
**Dependent on completion of #45** 

As Karyn the curator
I would like the ability to edit and approve the extracted text
So that I can correct errors in extracted text if they exist and confirm agreement with the raw data document.

On the QA check page (created in #45), there should be an 'Approve' and an 'Edit' button. 

If Karyn selects 'Approve,' the application must store the following information associated with that data document:
- user ID of the user who clicked on approve
- date and time the user clicked on approve
- indication that the text extraction was approved without errors

If Karyn selects 'Edit,' the uploaded text appearing on the QA check page should become editable, and an additional open text box for 'QA notes' should appear (open text box can be limited to <255 characters, with spaces). An entry into the 'QA notes' field should be required before the user can select 'Approve.' The 'Edit' button should be disabled since Karyn is already in Edit mode. When Karyn selects 'Approve' while in edit mode, the application must store the following information associated with the data document:
- user ID of the user who clicked on approve
- date and time the user clicked on approve
- any notes entered into the 'QA notes' box
- any edited text which as changed within the extracted text fields
- Indication that the text extraction was approved *with* errors

Definition of Done
- 'Approve' button on QA check page
- 'Edit' button on QA check page
- Ability to edit extracted text when in edit mode

**Comment by mwfrost** [comment]
I have some questions about the bold item below:

> When Karyn selects 'Approve' while in edit mode, the application must store the following information associated with the data document:
> 
> - user ID of the user who clicked on approve
> - date and time the user clicked on approve
> - any notes entered into the 'QA notes' box
> - **any edited text which as changed within the extracted text fields**
> - Indication that the text extraction was approved with errors

@kdionisio , do you have a vision of how this record of the edited text might be exposed to the user? If we are planning to implement a form of version control on the ExtractedText objects, it could get complicated.

Sorry I didn't notice this in time to ask more about it in the planning meeting.

**Comment by mwfrost** [comment]
Kathie,
When the user clicks "Edit," are you picturing the ExtractedChemical records in a sort of editable spreadsheet? Each value in a cell?

**Comment by mwfrost** [comment]
An example of what I mean:

http://django-datatable-view.appspot.com/x-editable-columns/

**Comment by kdionisio** [comment]
@mwfrost  Yes something like this would definitely work!

**Comment by debboutr** [comment]
@mwfrost once you approve ALL of the `ExtractedText` objects in the `QAGroup`, you will need to update the `QAGroup`'s `qa_complete` attr to `True`. The button @ `http://127.0.0.1:8000/qa/` for that script will still read `Continue QA`, but when it is clicked, it will create a new `QAGroup` instead of looking up the existing. it could be a method of the `QAGroup` that would be called after every `Approval` request is made, like so:

```
def update_qa_complete(self):
    assigned = ExtractedText.objects.filter(qa_group=self).count()
    checked = ExtractedText.objects.filter(qa_group=self, 
                                           qa_checked=True).count()
    self.qa_complete =  assigned == checked
    self.save()
```
_if this doesn't ever get switched to `True`, we will end up seeing an empty table here: `http://127.0.0.1:8000/qa/extractionscript/5`_

hope this makes sense!

**Comment by mwfrost** [comment]
I'd appreciate some brainstorming about how to test this ticket. 

Things I've built so far and need to write tests against:

- The ExtractedChemical child instances are displayed in a table under the ExtractedText instance's attributes
- The user can edit every attribute of every ExtractedChemical instance, and can add new ones
- The "Approve" button sets all the ExtractedText object's QA attributes and delivers the browser to the next ExtractedText detail page
- The "Save edits without approving" button lets the user save in-progress edits to the ExtractedChemical instances without approving the ExtractedText 
- The "Approve with edits" button saves the edits made to the ExtractedChemical instances, sets the ExtractedText QA attributes, and delivers the user to the next ExtractedText page

Things I have not yet done:
- Use the "Edit extracted chemicals" button to toggle the ExtractedChemical formset's status between read-write and read-only.

**Comment by mwfrost** [comment]
@kdionisio 
Kathie, how important is it that the page include this ability to toggle between editing and read-only modes? The modal behavior is not used anywhere else, and it involves a non-trivial amount of UI coding. 
If we remove the modal requirement, the form could still require some notes before allowing the user to save any edits. 
I'd just like to make sure that this is an essential piece of functionality, since it's going to involve more work and will introduce novel UI behavior.
