### ISSUE TITLE
scrape home depot product data (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#498]
Systematically scrape product data from Home Depot website using script created in #447.

Definition of done:
1. When product data is scraped, data is automatically pushed into the prod_racp database (a staging area for factotum)
2. any fields present in prod_racp which are available on a product page from Home Depot should be scraped
3. Any associated MSDS/SDS files linked to the product should be downloaded and linked to the product record in the staging database

Also set up to constantly check website for updates?

**Comment by dmlyons2** [comment]
@dmlyons2 will provide script for Walmart Scraping

**Comment by debboutr** [comment]
@dmlyons2 I'm trying to get this script ready to ship to you, but as I'm looking through the dependencies I'm now realizing that I moved to using selenium to scrape because some of the data on each page gets populated w/ JS and isn't available in the initial request. Anyway, I think that this will mean that you will have to go through the process of installing chrome and then the webdriver in order for this script to run as I have it. Does that seem okay to you? I don't know another way around it, the only data that we are gaining is the thumbnails of how the product is categorized w/in Home Depot:

Home  / Paint  / Interior Paint  / Countertop Paint 

if you go to this url you will see that this data gets added after initial page load

https://www.homedepot.com/p/Rust-Oleum-Specialty-29-oz-Countertop-Coating-Tint-Base-246068/202820906

Other than this, I am just adding a way to manage each of the urls after being searched so that if the script stops, when started again it will know to start where it left off.

**Comment by dmlyons2** [comment]
@debboutr  - This all sounds good - I can work with selenium.

**Comment by debboutr** [comment]
Here are the couple of scripts that I have worked out for collecting the hole depot data

https://github.com/debboutr/scrape_home_depot

along with them are a couple of ".npy" files that hold arrays that get read in w/ the "scraper.py" script.
One holds all of the URLs that we will go through, the other keeps URLs that are problematic. You can get them here:
https://drive.google.com/open?id=1xW2KkgZARVPt_1m0pyLYSDrohkOaFe_g

and they will have to be in the same directory as the "scraper.py" script that you can clone from the repo above.

The following packages are needed to run these scripts:

- beautifulsoup4
- pymysql
- numpy
- requests
- selenium
