### ISSUE TITLE
error when uploading extracted text

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#666]
When attempting to upload extracted text for a data group type 'Chemical Presence List' (CP), the following error was seen. Note that this is the first time we have attempted loading extracted text for the CP data group. We have tried a few different extracted text files and all result in the same error.

UnboundLocalError at /datagroup/90/
local variable 'record' referenced before assignment
Request Method:	POST
Request URL:	http://factotum.epa.gov/datagroup/90/

Django Version:	2.1.2
Exception Type:	UnboundLocalError
Exception Value:	local variable 'record' referenced before assignment
Exception Location:	/data/code/factotum/dashboard/views/data_group.py in data_group_detail, line 136

**Comment by kdionisio** [comment]
File user is attempting to upload, which is causing the above error (uploaded here as zip file but is being uploaded to Factotum as a .csv) . User is attempting to upload the attached file as extracted text for datagroup/90 on prod.

[Arizona_extract_template_2007-2010.zip](https://github.com/HumanExposure/factotum/files/2852098/Arizona_extract_template_2007-2010.zip)

**Comment by mwfrost** [comment]
I think one of the csv records is causing a validation error, and we are not handing that error properly.
This is in `views.data_group.py`
```
                try:
                    ext.full_clean()
                    ext.save()
                    record = ext_child(**row)
                    record.full_clean()
                except ValidationError as e:
                    context['ext_err'][i+1] = e.message_dict
                good_records.append((d,ext,record))
```
The `record` variable is assigned inside the `try:` block. If there's an exception, it adds the error to `ext_err` but still tries to add `record` to `good_records`

**Comment by debboutr** [comment]
@kdionisio few things that have come up with this ticket...

1. The `cpcat_code` field was set up to only hold 20 chars, the csv that you are using holds more than that. This draws up an Exception which I have figured out why it doesn't make it bakc to the page so you can see it. This I can fix but if you want to have 22 chars in this field it's always going to be an error.

2. Each of the other Extracted[x] types have used a field `prod_name` which we check must have a 1:1 relationship with the DataDocument, this was looked at in #555.  The ExtracteCPCat has a prod_name field, but it's never being populated from the csv, it would be simple enough to add to the template and then load and check inthe way that we do with the others, but that may not make sense for you guys.

3. Currently when this event occurs, the `ExtractedCPCat` record that is initially created and tehn begun to populate w/ `ExtractedListPresence` records will still linger in the DB even though this error would have come up. In my assessment, this is probably okay. I'd imagine that the errors will be fixed in the CSV and then it will be run again until it is successful. Thought this would be good to know about anyway.

**Comment by kdionisio** [comment]
@debboutr For the record, per our phone conversation - 
1. increase length of the cpcat_code field to be max 50 characters
2. the 'cat_code' field for this model can be used in the way that the 'prod_name' field was used for other extracted text models
3. prefer to have the records deleted if an error is thrown
