### ISSUE TITLE
custom QA workflow by data group type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#679]
As the product owner
I would like to make the QA workflow for a data document dependent on data group type
So that I can complete QA appropriate for data documents of different group types

Definition of Done:
- QA workflow is dependent on data group type
- current QA workflow (based on extraction script) is applicable to data group type CO

**Comment by debboutr** [comment]
here is some freewheelin'...

We are listing the Script used for DL in each DataGroup detail view as well as each DataDocument detail view. What we need for QA is access to the `'EX'` script which is associated with ExtractedText record. This could be in each of these detail views, if it it exists, and then could easily be informed by whether or not there is a QAGroup record that isn't `qa_complete` for that given script. This way we can have an html element/s that could state this scripts name as well as whether or not there has been any QA done on it yet, or whatever the state of QA is currently, (QA Begin/Continue/Complete).

So, if the state on either the DG detail or DD detail page of a script is `'Begin'` we can have a link to a view which will do the random assignment amongst **all** of the docs that are related to that script. So where do we go back to? none of the docs in that DG detail group may have been picked OR the doc whose detail page you were just on may not have been picked, right? I'm thinking here, we would return to the DG detail page and we can build into it the ability to sort/filter docs that are in the QAGroup for that script. I'm thinking down the road, we can have a checkbox selector to add documents to a QAGroup if it already exists for a Script and isn't yet `qa_complete`

For any of the `auto` extraction types CP, FU,... _we could_ create acces to the QA process from both DG detail and DD detail views. The state of each document's QA is in the ExtractedText record, and the state of QA for the script can be deduced from this and the QAGroup state. We could have a link to the QA view from either and if coming from the DDoc and it hasn't yet been `qa_approved` that would be the first on to be looked at in the QA view.

I'm glossing over a lot, but in my mind this could all be implemented fairly simply so that the state of QA is in the user's eyeballs in more places. It'd be much easier for me to talk through.

**Another quick detail about Group Type**
We are maintaining the `'UN'` type. I can understand that we might import DataDocuments with this type, but do we have DDocs that are extracted that are of this Group Type. To me it seems strange that we have extracted data from docs like these, but they aren't identified as being a specific type. In my mind the UN type would just follow what we are doing with the `'CO'` composition types, but I was thinking that maybe DataDocuments should only be `UN` unidentified up until the  point of extraction. Does this make sense? It seems strange for us to have docs in factotum and for it to have gone through QA and for us to have a descriptor that says we haven't identified what type of doc this is, but maybe it's just the word we are using for that Group Type. Should we use `'WC'` "wild card", `'ST'` "strange", `'AN'` "anomalous"

**Comment by kdionisio** [comment]
closing because ticket is no longer applicable
