### ISSUE TITLE
extracted CP data not displaying on data doc page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#751]
When entering a new set of extracted text for a CP data document using the new webform functionality for manual data entry, the data entered is not displayed on the data doc page after saving in the modal window. In addition, if one selects 'edit' the modal window brings the extracted CP fields back up but does not show any values in them (they appear blank, even though I have confirmed that the data entered did save in the database)

Definition of Done:
After entering and saving CP data in modal window, data should be displayed on the CP data document page.
Fields to display (from extractedcpcat model), in addition to those already being displayed in the 'extracted text' box on the data doc page:
- cat_code (labeled as 'cat_code')
- description_cpcat (labeled as 'CPCat cassette')
- cpcat_code (labeled as 'ACToR snaid')
- cpcat_sourcetype (labeled as 'CPCat source')

**Comment by debboutr** [comment]
oh, shoot. well, this is certainly my fault, but I don't think it'll be much of a problem to get right. The 'CP' type docs had always only shown just those fields which we are seeing.
![image](https://user-images.githubusercontent.com/7052993/54414528-b4092080-46b6-11e9-993e-a9d56e8866e5.png)

I'm not sure why I made the form different once the ExtractedText object was instantiated, but I don't think that's what we want. If you notice when you originally add the ExtractedText the window holds all of the fields including `prod_name` etc.  But once you go back to edit it is different. It probably shouldn't be. 

This ref's #680 and #677. I'm not sure why I changed the form fields to present in the window to be different once the ExtractedText was made on the initial submission, I may have a good reason, but I can't think of it right now.

here are the fields for `HH` type in the initial form, strikethroughs don't come back in the form after ExtText is made:

- ~~'prod_name',~~
- ~~'doc_date',~~
- ~~'rev_num',~~
- 'hhe_report_number',
-  'study_location',
-  'naics_code',
-  'sampling_date', 
- 'population_gender',
-  'population_age', 
- 'population_other', 
- 'occupation', 
- 'facility'

here are the fields for `CP` type, again, strikethroughs only appear if the ExtText is not yet created:

- ~~'prod_name',~~
- 'doc_date', 
- ~~'rev_num',~~
- ~~'cpcat_code'~~
- 'cat_code',
- 'description_cpcat',
- 'cpcat_sourcetype'

So the above we can figure out easily in terms of what to display and when. The fact that the form inputs aren't populating is a bug that stems from this bit of code:
```
extracted_text = doc.extractedtext.pull_out_hh()

    # above would get us the HH object or the ExtractedText object, but not CPCat, 
    # so the solve is below on line 30 of the data_document_detail view.

extracted_text = ExtractedText.objects.get_subclass(pk=pk) 
```
Sorry about the confusion here, I feel like I have been spinning ever since I heard I was going to be moving to NC for a while.

**Comment by mwfrost** [comment]
To find records for testing, use this query:
```

select * from dashboard_datadocument dd 
inner join dashboard_datagroup       dg
on dd.data_group_id = dg.id
inner join dashboard_grouptype       gt
on dg.group_type_id = gt.id
where gt.code IN('HH','CP')
AND dd.id NOT IN 
(SELECT data_document_id from dashboard_extractedtext)
;

```

**Comment by mwfrost** [comment]
Pages to test in the browser:

http://127.0.0.1:8000/datadocument/354784/ (HHE)

http://127.0.0.1:8000/datadocument/254782/ (CPCat)
