### ISSUE TITLE
stub UPC populating with previously used stub UPC

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#765]
When using the 'create new product' form (http://factotum.epa.gov/link_product_form/271937/) to add a product for a data document, the UPC field automatically populates with a stub UPC (which can be changed if the user has a true UPC to enter).

Currently, the link product form UPC field is populating with 'stub_556233', a UPC which has already been used for a different product:  http://factotum.epa.gov/product/556244/

This is preventing us from manually adding any new products with stub UPCs to the system.

In addition, I get the following bug when attempting to bulk create products for a data group from the data group page (http://factotum.epa.gov/datagroup/198/)

IntegrityError at /datagroup/198/
(1062, "Duplicate entry 'stub_556233' for key 'upc'")

Thus we also can not bulk create products within the application.

Definition of Done:
- Ability to create products in the application without duplicate stub UPC errors
    - Link product form populates with a stub UPC that does not already exist in Factotum.
    - Bulk create products button functions without an error

**Comment by dmlyons2** [comment]
Only do enough to fix this issue

**Comment by debboutr** [comment]
![image](https://user-images.githubusercontent.com/7052993/54776346-2608ca80-4bcd-11e9-9120-9cb0da5dd16d.png)

this problem was created from the user deleting a Product, which reduced the count of products by 1.
in the `link_product_form` view we are using the count to create what should be a unique value for UPC

`'stub_' + str(Product.objects.all().count() + 1)`

this uniqueness does not jive with the way that we are currently arriving at the integer value appended to "stub_" if a product is deleted. 

- we could solve by just using a UUID here, we have 60 chars to fill in this field
- we could recursively increment in a function until we get a value we know to be unique

```
def just_figure_it_out(already=1):
    stub_val = 'stub_' + str(Product.objects.all().count() + already)
    if not Product.object.filter(upc=stub_val).exists():
        return stub_val
    else:
        return just_figure_it_out(already+1)
```
then on line 89 of `product_curation.py` we'd add
`initial = {   'upc': just_figure_it_out(),`

- or, lastly, what might be the best way might be to get the largest pk int he DB and increment by 1 similarly to what we were doing but to adapt for deletes instead of using COUNT we just get the latest record in the DB's pk and increment

`'stub_' + str(Product.objects.first().pk + 1)`

any of these will work, but each has it's own implementation considerations

**Comment by dmlyons2** [comment]
Please put an estimate in on this issue
