### ISSUE TITLE
Elasticsearch Search Landing Page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#797]
As a Factotum user
I want to search for a chemical and return the top 10 documents ~and PUCs~ containing that chemical
So that I can provide this information to interested partners and clients

Definition of Done
1. User enters chemical name, CAS, or SID in search box. Search should search on the raw_cas and raw_chem_name fields (in dashboard_rawchem), and on the  true_cas, true_chemname, and sid fields (in dashboard_dsstoxlookup)

2. Landing page returns:
  - top 10 data documents containing the chemical searched for, including the following
      - data document title (title field from dashboard_datadocument model). Only display the first 60 chars of the title followed by ellipsis if it is greater than 60. Make the tooltip for the title the full title value.
      - data document title is hyperlink to data document page
     - number of products associated with that data document
 - build first to a separate URL and page than current search so that we can swap old search with new search in a future sprint

**Comment by dmlyons2** [comment]
![2_797_ElasticSearchLanding](https://user-images.githubusercontent.com/1336349/57017670-bf23fb80-6be5-11e9-8ed9-084f37fba7e5.png)

**Comment by mwfrost** [comment]
Is it the case that the results should not display any of the chemical attributes (raw or curated) that caused the search to find them?

**Comment by mwfrost** [comment]
You can see in this example that I have split out the results by chemical rather than just by data document. If that's incorrect, I will aggregate the results so that each data document only appears once, but then the chemical names that cause the document to be selected will have to be displayed some different way. Or not at all.

<img width="758" alt="sc_2019515_9228_589" src="https://user-images.githubusercontent.com/201835/57792047-fb318300-76f2-11e9-904c-f4d5c08eddde.png">
