### ISSUE TITLE
Expand Elasticsearch for PUCs

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#825]
This is a an expansion of #797

As a Factotum user
I want to search for a chemical and return the top 10 PUCs containing that chemical
So that I can provide this information to interested partners and clients

Definition of Done

Landing page developed in #797 returns results defined in #797 plus
  - top 10 PUCs containing the chemical searched for, including the following
      - name of each PUC
      - number of products in each PUC that contain the chemical searched for

**edit 6/4/2019 KD - limit search results to only the 'formulation' kind of PUCs

**Comment by mwfrost** [comment]
Should the results be summarized at the PUC level without any disaggregation for document or chemical? A search for "*paraben" will return results for both "methylparaben" and "ethylparaben". If there are products under PUC 185 that contain methylparaben, ethylparaben, or both, should they be listed separately? Counted separately?

This is worth thinking about now, because in ticket #810 , the product count becomes a hyperlink to a new view:

> On the elastic search landing page created in #825, the number of products in each PUC which contain the chemical searched for should link to a page listing all of those products

It seems to me that "the chemical searched for" can be a collection of different chemicals. Should the new page display all the potential matching chemicals from the original search string?
