### ISSUE TITLE
integrity error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#839]
Discovered integrity error within production version of Factotum.

To reproduce
1. From this data document page: http://factotum.epa.gov/datadocument/281282/
2. Select the blue pencil 'editing' button in the 'Extracted Text' section of the page
3. Edit the product name field in the modal pop up editing window
4. Save edits
5. See integrity error

Definition of Done:
Resolve integrity error

**Comment by mwfrost** [comment]
<img width="672" alt="sc_2019425_11186_903" src="https://user-images.githubusercontent.com/201835/56758580-d7aa9680-674b-11e9-85f6-8f9fbe787406.png">

**Comment by mwfrost** [comment]
I see what's going on.

In line 142 of `views/data_document.py`, we are using the `get_or_create()` convenience method with two arguments: the extraction script and the document's pk. We are passing that script object as an argument only in case the method has to invoke the "create" option. But `get_or_create()` first tries to `get()` a record with the specified parameters, so it is looking for an extractedtext object where pk=281282 and the extraction_script is "Manual (dummy)". 

Because there is no such record, the `get_or_create()` method thinks it has to create a new ExtractedText object with pk= 281282. It tries to do so and fails.

We need to change this so that `get_or_create()` is only told to look for a pk. Then we can use the `created` value that it returns to assign the "Manual" script if `created=True`.

I bet if you tried this on any other ExtractedText record where the script is not the "Manual" default, you'd see the same error.

**Comment by mwfrost** [comment]
I made a corrected branch and pushed it up while `dev` and `master` were still the same, just so that this would have the option of becoming a hotfix. 

https://github.com/HumanExposure/factotum/tree/839_fix_integrity_error

**Comment by mwfrost** [comment]
My proposed fix to `views/data_document.py`:
Old:
```
    exttext, _ = model.objects.get_or_create(extraction_script=script,
                                             data_document_id=pk)
```
New:
```
    exttext, et_created = model.objects.get_or_create(data_document_id=pk)
    if et_created:
        exttext.extraction_script=script
        exttext.save()
```

**Comment by debboutr** [comment]
won't we want to store the fact that this extext record has been extracted using a script but we have had to manually change in the interface?? we have the `qa_edited` field in the ExtractedText model, but is this really QA editing? it's coming from the DD detail page

**Comment by mwfrost** [comment]
That is a good question about how the business logic should work. It can be addressed in whatever ticket follows the hotfix.
