### ISSUE TITLE
add report_funcuse field for CP data type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#916]
As a Factotum user
I want to be able to store the reported functional use for a CP data group type
So that I can maintain relevant information provided by a CP source

Definition of Done:
- ability to store report_funcuse field in dashboard_extractedcpcat model (varchar(100))
- report_funcuse column should appear in the template for the extracted text upload for group type CP
- upload of extracted text for group type CP should accept report_funcuse column

**Comment by mwfrost** [comment]
@kdionisio The `dashboard_extractedcpcat` table is the parent object of the `ExtractedCPCat:ExtractedListPresence` relationship. It corresponds to `ExtractedText` in the `ExtractedText:ExtractedChemical` relationship. Is `dashboard_extractedcpcat` the appropriate place to store the reported functional use? Functional use, as I understand it, is a chemical-specific property, which is why we store it on the ExtractedChemical object, not the ExtractedText object. 

Please let me know if I should proceed with the ticket as written.

**Comment by mwfrost** [comment]
@kdionisio  Another question: should this field be visible in the data document detail page and/or the QA page for CP records?

**Comment by debboutr** [comment]
@mwfrost for the way I'm adjusting the detail page, if it's in the form as visible, it'll be in the page, please don't bother editing the detail.html, it'll all be for naught anyway

**Comment by kdionisio** [comment]
I'm not looking at the DB right now, but yes, you are correct that the
functional use is a chemical specific property. So if that means it should
be a field in extractedlistpresence (as the correlary to extractedchemical)
then I agree!

Regarding if the field should be visible in the data document detail page
and/or the QA page - I did not bother requesting this since these pages are
being redone now anyways. So short answer is no!
